<?php
// Make sure we aren't being loaded directly!
if ( ! defined( 'ABSPATH' ) ) {
	exit();
}

/**
 * Class TM_LCPTU_Widget
 * @since 2.0.0
 */
class TM_LCPTU_Widget extends WP_Widget {

	/**
	 * TM_LCPTU_Widget constructor. Sets up our widget.
	 * @since 2.0.0
	 */
	function __construct() {
		$id_base        = false;
		$name           = _x( 'Latest Custom Post Type Updates', 'widget name', 'latest-custom-post-type-updates' );
		$widget_options = array(
			'description' => _x( 'Displays the most recent posts from builtin and custom post types.', 'widget description', 'latest-custom-post-type-updates' ),
		);

		parent::__construct( $id_base, $name, $widget_options );
	}

	/**
	 * Outputs our widgets html markup
	 *
	 * @param array $args
	 * @param array $instance
	 *
	 * @since 2.0.0
	 */
	function widget( $args, $instance ) {
	}

	/**
	 * Sanitizes and saves our widget options
	 *
	 * @param array $new_instance
	 * @param array $old_instance
	 *
	 * @return array
	 * @since 2.0.0
	 */
	function update( $new_instance, $old_instance ) {
		return parent::update( $new_instance, $old_instance ); // TODO: Change the autogenerated stub
	}

	/**
	 * Options for our widget
	 *
	 * @param array $instance
	 *
	 * @return string
	 * @since 2.0.0
	 */
	function form( $instance ) {
		return parent::form( $instance ); // TODO: Change the autogenerated stub
	}

}